// Regenerate src/standard.ts from gemoji's published database - the
// "referenced standard table" the spec names (SPEC.md, "Emoji"): Marquee
// does not invent or maintain the 3,000-entry table, it repackages the
// standard one. Re-runnable; this is the ONLY thing that ever talks to the
// network - consumers get the committed, generated table.
//
//     npm run fetch-standard

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const DB_URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json";
const LICENSE_URL = "https://raw.githubusercontent.com/github/gemoji/master/LICENSE";

// Marquee's slug grammar (SPEC.md, "Emoji"): lowercase letters, digits,
// `_`, `+`, `-`, at most 64 bytes. Everything in gemoji conforms today;
// filter anyway so a future upstream addition cannot smuggle in a slug the
// parser will never match.
const SLUG = /^[a-z0-9_+-]{1,64}$/;

interface GemojiEntry {
  emoji?: string;
  aliases: string[];
}

const res = await fetch(DB_URL);
if (!res.ok) {
  throw new Error(`gemoji db fetch failed: ${res.status}`);
}
const db = (await res.json()) as GemojiEntry[];

const table = new Map<string, string>();
let skipped = 0;
for (const entry of db) {
  if (entry.emoji === undefined) {
    continue; // non-unicode entries (GitHub's custom images): not ours
  }
  for (const alias of entry.aliases) {
    if (!SLUG.test(alias)) {
      skipped += 1;
      continue;
    }
    if (!table.has(alias)) {
      table.set(alias, entry.emoji);
    }
  }
}

const lines = [...table.entries()]
  .sort(([a], [b]) => (a < b ? -1 : 1))
  .map(([slug, emoji]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(emoji)},`);

const out = `// GENERATED by scripts/fetch-standard.ts from gemoji's database - do not
// edit by hand (npm run fetch-standard regenerates). Data: github/gemoji
// (MIT; see GEMOJI-LICENSE). ${table.size} shortcodes.

export const STANDARD: Record<string, string> = {
${lines.join("\n")}
};
`;

writeFileSync(fileURLToPath(new URL("../src/standard.ts", import.meta.url)), out);

const license = await fetch(LICENSE_URL);
if (license.ok) {
  writeFileSync(
    fileURLToPath(new URL("../GEMOJI-LICENSE", import.meta.url)),
    await license.text(),
  );
}

console.log(`standard table: ${table.size} shortcodes${skipped > 0 ? `, ${skipped} non-conforming slugs skipped` : ""}`);
