// Fetch the grab-bag fonts: for every non-standard name in the FONTS
// vocabulary, download the latin WOFF2 from Google Fonts plus its OFL
// license text, and regenerate css/fonts.css. Re-runnable; skips files that
// already exist. This is the ONLY thing that ever talks to a font CDN -
// readers never do (fonts are self-hosted on principle; see fonts/README.md).
//
//     npm run fetch-fonts

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { FONTS } from "../src/index.ts";

const STANDARD = new Set(["sans", "serif", "mono", "comic"]);
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

/** Google's family name where it differs from our canonical face name;
 * candidates are tried in order (@font-face re-aliases to our name). */
const GOOGLE_FAMILY: Record<string, string[]> = {
  bitcount: ["Bitcount", "Bitcount Prop Single", "Bitcount Grid Double"],
};

const fontsDir = fileURLToPath(new URL("../../../fonts/", import.meta.url));
const cssPath = fileURLToPath(new URL("../../../css/fonts.css", import.meta.url));
mkdirSync(fontsDir, { recursive: true });

async function fetchText(url: string): Promise<string | null> {
  const res = await fetch(url, { headers: { "user-agent": UA } });
  return res.ok ? res.text() : null;
}

async function latinWoff2Url(family: string): Promise<string | null> {
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${family.replaceAll(" ", "+")}`,
  );
  if (css === null) {
    return null;
  }
  // The response is @font-face blocks per subset, each preceded by a
  // comment like /* latin */ - take the plain-latin one.
  const m = /\/\* latin \*\/\s*@font-face\s*{[^}]*?url\((https:[^)]+\.woff2)\)/.exec(css);
  return m?.[1] ?? null;
}

const done: string[] = [];
const failed: string[] = [];
const faces: Array<{ token: string; family: string }> = [];

for (const [token, family] of Object.entries(FONTS)) {
  if (STANDARD.has(token)) {
    continue;
  }
  const woff2Path = join(fontsDir, `${token}.woff2`);
  const oflPath = join(fontsDir, `${token}.OFL.txt`);
  const candidates = GOOGLE_FAMILY[token] ?? [family];

  let resolved: string | null = null;
  for (const candidate of candidates) {
    const url = await latinWoff2Url(candidate);
    if (url !== null) {
      resolved = candidate;
      if (!existsSync(woff2Path)) {
        const res = await fetch(url, { headers: { "user-agent": UA } });
        if (!res.ok) {
          resolved = null;
          continue;
        }
        writeFileSync(woff2Path, Buffer.from(await res.arrayBuffer()));
      }
      break;
    }
  }
  if (resolved === null) {
    failed.push(token);
    continue;
  }

  if (!existsSync(oflPath)) {
    const dir = resolved.toLowerCase().replaceAll(" ", "");
    const ofl = await fetchText(
      `https://raw.githubusercontent.com/google/fonts/main/ofl/${dir}/OFL.txt`,
    );
    if (ofl !== null) {
      writeFileSync(oflPath, ofl);
    } else {
      console.error(`  ! ${token}: woff2 fetched but OFL.txt not found (dir guess: ${dir})`);
    }
  }
  faces.push({ token, family });
  done.push(resolved === family ? token : `${token} (via "${resolved}")`);
}

// css/fonts.css: every face declared under OUR canonical family name, so
// marquee.css stacks match regardless of the source family's exact name.
const rules = faces
  .map(
    ({ token, family }) => `@font-face {
  font-family: "${family}";
  src: url("../fonts/${token}.woff2") format("woff2");
  font-display: swap;
}`,
  )
  .join("\n\n");
writeFileSync(
  cssPath,
  `/* fonts.css - generated by fetch-fonts.ts; self-hosted faces for the\n * closed font list. Serve fonts/ alongside css/. */\n\n${rules}\n`,
);

console.log(`fetched ${done.length} faces: ${done.join(", ")}`);
if (failed.length > 0) {
  console.error(`FAILED (${failed.length}): ${failed.join(", ")}`);
  process.exit(1);
}
